# Generated by Django 4.2 on 2024-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_deliveryaddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
