# Generated by Django 4.2 on 2024-11-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_deliveryaddress_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='zipcode',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
